// Escenas editoriales ficticias. Los hechos y cifras vienen del balance,
// no de estos chistes. Cada banco tiene al menos quince textos completos.
export const NEWSPAPER_HEADLINES = {
  crisis: [
    'Pipo propone declarar potable el discurso',
    'el comité de baldes exige respuestas',
    'Sofía guarda la cinta de inaugurar',
    'el optimismo no sale por la canilla',
    'Pipo trae un PowerPoint con agua dibujada',
    'el balde pide audiencia urgente',
    'Jacinto devuelve el folleto de milagros',
    'la rana suspende los aplausos',
    'Berta cancela el brindis imaginario',
    'el comunicado no llenó ni una taza',
    'Pipo propone regar las promesas',
    'el valle necesita agua, no un eslogan',
    'Ferrada apaga el ventilador de excusas',
    'el sello municipal tampoco da agua',
    'Pipo busca la canilla del presupuesto'
  ],
  error: [
    'Pipo culpa al horóscopo de la canilla',
    'el comité recomienda menos discursos',
    'Sofía pide revisar antes de inaugurar',
    'el balde no acepta excusas en cuotas',
    'la rana exige leer la letra chica',
    'Jacinto archiva el plan «ya veremos»',
    'Pipo propone una comisión de comisiones',
    'el acta salió húmeda de preocupación',
    'Berta le baja el volumen al optimismo',
    'Ferrada pide un plan que no sea un meme',
    'el valle devuelve el folleto triunfal',
    'Pipo busca dónde se enchufa la lluvia',
    'la canilla no entendió el comunicado',
    'Sofía retira el cartel de «todo joya»',
    'el megáfono no mejora el reparto'
  ],
  recovery: [
    'Pipo se atribuye todo desde la reposera',
    'el balde retira su carta de renuncia',
    'Sofía guarda el manual de excusas',
    'la rana levanta el paro de aplausos',
    'Berta jubila una pancarta',
    'Jacinto ofrece tregua al zapallo',
    'Ferrada manda al casco a descansar',
    'Pipo cobra por haber mirado',
    'el comité suspende la reunión urgente',
    'Sofía respira; Pipo pide una medalla',
    'la vaca dice que fue idea suya',
    'el optimismo vuelve sin escribano',
    'Jacinto cancela la visita al cactus',
    'la rana cambia quejas por croares',
    'Pipo manda imprimir su autobiografía'
  ],
  normal: [
    'Pipo pide dietas por vigilar una canilla',
    'La vaca exige silla en la mesa del agua',
    'Jacinto descubre al zapallo haciendo lobby',
    'Sofía prohíbe regar con comunicados',
    'El espantapájaros pide viáticos en semillas',
    'Ferrada rechaza enfriar máquinas con memes',
    'La rana pide actas resistentes al agua',
    'Pipo inaugura la oficina de esperar lluvia',
    'Berta encuentra al toro ensayando discursos',
    'El cactus vende cursos de paciencia',
    'El balde se postula como asesor del valle',
    'Pipo exige estacionamiento para su flotador',
    'Jacinto negocia con la comisión de tomates',
    'La canilla pide licencia por tanta reunión',
    'Sofía busca un trámite que no tenga sed'
  ],
  good: [
    'Buen reparto: Pipo pide una estatua flotante',
    'El valle festeja; la vaca se come el programa',
    'Jacinto condecora al espantapájaros',
    'Sofía celebra; Pipo factura los aplausos',
    'Ferrada trae una torta con forma de compuerta',
    'La rana declara feriado para las planillas',
    'El zapallo exige salir en la foto del festejo',
    'Pipo ensaya el discurso; Berta apaga el micrófono',
    'El valle brinda; el balde pide copa propia',
    'Sofía inaugura cinco minutos sin reclamos',
    'La vaca propone repartir medallas comestibles',
    'Jacinto pide música; el gallo cobra derechos',
    'Ferrada autoriza al casco a bailar',
    'Pipo corta una cinta: era la soga del tendedero',
    'Reparto logrado; la rana pide repetir sin discursos'
  ],
  opportunity: [
    'Pipo negocia; exige recibo de las hojas',
    'Sofía firma antes de que el sello pida viáticos',
    'Jacinto descubre al zapallo leyendo el contrato',
    'Berta cierra el acuerdo; la vaca pide una copia',
    'Ferrada busca la cláusula del mate',
    'El comité aprueba algo: Pipo llama a la prensa',
    'Sofía retira el adorno para encontrar la propuesta',
    'Pipo trae tres sellos y ninguna lapicera',
    'La rana solicita contrato en idioma charco',
    'Jacinto firma; el espantapájaros cobra comisión',
    'Berta rechaza pagar al asesor con alfalfa',
    'Ferrada pide menos ceremonia y más letra clara',
    'El balde quiere figurar como testigo',
    'Pipo ofrece garantía: una hoja plastificada',
    'Sofía anuncia un acuerdo; el toro reclama invitación'
  ],
  qualityDrop: [
    'Baja la calidad: Pipo ofrece un colador de juguete',
    'La rana rechaza el perfume para el río',
    'Clara retira el pincel del plan de Pipo',
    'Calidad en caída: el filtro no acepta discursos',
    'Pipo propone agua fotogénica; Clara pide tratamiento',
    'El colador pide no ser citado como tecnología',
    'La rana cancela el concurso de agua perfumada',
    'Pipo descubre que celeste no significa limpia',
    'Clara devuelve el plan de filtrar con una media',
    'El río no mejora con un filtro de Instagram',
    'Pipo quiere lavar el informe; Clara revisa el agua',
    'La rana pide análisis, no una presentación bonita',
    'Clara prohíbe confundir diluir con hacer magia',
    'El colador de Pipo no pasó la entrevista',
    'Pipo trae brillantina; Clara le señala el tratamiento'
  ]
} as const;
