// Sátira de un diario local: escenas editoriales, no sucesos simulados.
// Cada texto cambia el ángulo del chiste; los hechos van en la bajada.
export const NEWSPAPER_HEADLINES = {
  crisis: [
    'el comunicado recomienda conservar la calma restante',
    'la reunión urgente quedó para después del almuerzo',
    'se busca responsable; sobran candidatos a ausente',
    'el plan de contingencia estaba en una carpeta sin abrir',
    'los vecinos preguntan por la edición sin eufemismos',
    'la conferencia terminó antes de la primera pregunta',
    'ofrecen explicaciones con entrega inmediata',
    'el optimismo oficial requiere una segunda opinión',
    'la foto de archivo vuelve a trabajar horas extra',
    'el pronóstico de ayer solicita derecho a réplica',
    'la emergencia no figura en la agenda del asesor',
    'el protocolo tiene índice; falta encontrar el plan',
    'los reclamos superan la capacidad de la ventanilla',
    'Pipo anuncia que estuvo preocupado desde el principio',
    'el valle pide soluciones antes de la próxima cadena local'
  ],
  error: [
    'el informe reconoce un pequeño detalle pendiente',
    'la planilla cierra; la explicación todavía no',
    'Sofía solicita una versión menos creativa del balance',
    'la letra chica ocupa ya la portada',
    'los asesores aconsejan revisar sus propios consejos',
    'el comité descubre la utilidad de preguntar antes',
    'la previsión tenía margen, pero para el otro lado',
    'se posterga el anuncio de que estaba todo previsto',
    'el manual no trae capítulo sobre admitir errores',
    'la respuesta oficial llegó a la pregunta equivocada',
    'el visto bueno pasa a llamarse visto más o menos',
    'Pipo propone clasificar el problema como anécdota',
    'el trámite avanza más rápido que la solución',
    'la advertencia estaba al dorso del afiche',
    'la reunión dejó acuerdos para otra reunión'
  ],
  recovery: [
    'Pipo prepara sus memorias del esfuerzo ajeno',
    'los reclamos vuelven al horario de oficina',
    'el informe admite buenas noticias sin nota al pie',
    'el valle concede una tregua al grupo de WhatsApp',
    'la ventanilla recibe su primer agradecimiento',
    'el asesor encuentra su firma en el plan que criticaba',
    'Sofía permite guardar el teléfono de emergencias',
    'los vecinos recuperan tiempo para discutir de fútbol',
    'la oposición a la mejora solicita más pruebas',
    'el pronóstico pesimista pierde un suscriptor',
    'la redacción cambia el café urgente por café normal',
    'la asamblea termina antes de que cierre la panadería',
    'el consejo descubre que corregir también cuenta',
    'Jacinto retira una queja, pero guarda la copia',
    'el optimismo vuelve en período de prueba'
  ],
  normal: [
    'Avisos: se busca asesor que también escuche',
    'Pipo pide un cargo; todavía no eligió para qué',
    'Carta de lectores: «¿El trámite incluye la espera?»',
    'La agenda del valle vuelve a tener asuntos pendientes',
    'Entrevista al comité: respondieron por escrito',
    'El estacionamiento del consejo tiene más consenso que el plan',
    'Jacinto pide una reunión que no coincida con el riego',
    'El acta registra unanimidad entre quienes se quedaron',
    'Sofía intenta explicar el reparto sin diapositivas',
    'Berta pregunta si el horario rural contempla madrugar',
    'La redacción recibe una primicia que ya era pública',
    'Ferrada solicita un formulario con espacio para la respuesta',
    'El valle discute prioridades; el café gana por unanimidad',
    'La agenda promete brevedad en un documento de varias páginas',
    'Clara pide que el río figure también en el orden del día'
  ],
  good: [
    'Buen reparto: el valle consigue una noticia sin «pero»',
    'Sofía celebra sin convocar una conferencia',
    'Los vecinos felicitan al equipo; Pipo se acerca a la foto',
    'Jacinto brinda por una estación que no pidió milagros',
    'La redacción guarda el título de emergencia',
    'Carta de lectores: «Esta vez, gracias»',
    'Berta trae facturas; nadie pregunta por el presupuesto',
    'Clara celebra una buena noticia también para el río',
    'Ferrada reconoce un mérito que no cabe en su currículum',
    'El consejo logra algo más que aprobar el acta anterior',
    'El festejo tiene agua; el discurso, límite de tiempo',
    'Pipo ofrece inaugurar lo que ya funciona',
    'El valle brinda por el reparto, no por la presentación',
    'Se suspende la queja habitual por falta de argumentos',
    'Buenas noticias: el equipo comparte mérito y última medialuna'
  ],
  opportunity: [
    'Pipo firma como testigo y pide figurar como autor',
    'El consejo descubre una propuesta debajo de la carpeta',
    'La letra chica consigue un lector voluntario',
    'Sofía pregunta qué cuesta después de la foto',
    'El acuerdo pasa del discurso al expediente',
    'Jacinto recomienda leer antes de aplaudir',
    'Berta pide condiciones, no una visita protocolar',
    'Ferrada negocia con la calculadora encendida',
    'El asesor trae un sello; el valle pide un criterio',
    'Carta de lectores: «¿Quién se ocupa el lunes?»',
    'La propuesta sobrevive a su propia presentación',
    'El comité aprueba algo sin pedir otro comité',
    'Clara reserva una silla para las consecuencias',
    'Avisos: se busca responsable para la parte difícil',
    'El brindis queda sujeto a las condiciones del acuerdo'
  ],
  qualityDrop: [
    'Baja la calidad: el comunicado sigue impecable',
    'Clara pide análisis antes de aprobar el eslogan',
    'La transparencia del informe no alcanza para el agua',
    'Sofía devuelve el folleto que decía «todo bajo control»',
    'El tratamiento no admite reemplazo por una campaña',
    'La foto del río queda fuera del control de calidad',
    'Ferrada pregunta por el dato detrás del adjetivo «limpia»',
    'Carta de lectores: «El color bonito no es un análisis»',
    'El consejo descubre que diluir no borra el problema',
    'La redacción solicita menos adjetivos y más tratamiento',
    'Pipo propone mejorar la imagen; Clara señala los retornos',
    'El protocolo exige muestras, no declaraciones',
    'La calidad perdió terreno; el optimismo no es un filtro',
    'El informe trae portada brillante y contenido incómodo',
    'La promesa de agua mejor solicita fecha de cumplimiento'
  ]
} as const;
